### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by donghwan-shin**
WIP to inspect why Pylot does not generate any results after a simulation

### CODE REVIEW

**Comment by donghwan-shin** [comment]
@rsomers1998 Thanks a lot for your contributions! Do you think the new bug you found is now fixed with https://github.com/ADS-Testing/SAMOTA/pull/5/commits/4304713d0f3c3e337322019e2e80a3a238ad641b? 

Also, do you mind if we keep this branch for debugging and put `implementation/runner/run_SAMOTA_c.py` into another branch, e.g., causal-testing?

**Comment by rsomers1998** [comment]
Apologies, I did not mean to commit that file. It has been removed from this branch.

The other bug appears to be a versioning issue with `protobuf`. The suggested fix is to `Downgrade the protobuf package to 3.20.x or lower.` as we are currently using `4.25.0`. I have not messed with this and am just using the workaround for now as I don't know what is causing the dependency and what other versions/interfaces may need to be changed.

**Comment by rsomers1998** [comment]
Turns out `protobuf` could just be downgraded without breaking anything. This fixes the warning (https://github.com/ADS-Testing/SAMOTA/issues/6#issuecomment-1794926969) and also issue #8

**Comment by rsomers1998** [comment]
Commit a5dcb30 seems to fix simulation not acknowledging `finished.txt`. Simulation does not always wait the full 660 seconds now

**Pull request merged**
